In [4]:
from util_download_data_from_url import download_data_from_url
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
import pandas as pd 

In [8]:
data = pd.read_csv("../tmp/mail_spam_ham_data.csv")
train_data, test_data = train_test_split(data.values, test_size=0.2)
train_data[0:2, :]

array([['ham',
        "Call me when you/carlos is/are here, my phone's vibrate is acting up and I might not hear texts"],
       ['spam',
        "For ur chance to win a £250 cash every wk TXT: ACTION to 80608. T's&C's www.movietrivia.tv custcare 08712405022, 1x150p/wk"]],
      dtype=object)

In [7]:
X = train_data[:, 1]
y = train_data[:, 0]

In [36]:
vectorizer = CountVectorizer(ngram_range=(1,2))
vectorizer.fit(X[:2])
voca = vectorizer.vocabulary_
print(len(voca))
print(voca.keys())
print(voca)
print(X[:2])

22
dict_keys(['reverse', 'is', 'cheating', 'that', 'not', 'mathematics', 'reverse is', 'is cheating', 'cheating that', 'that is', 'is not', 'not mathematics', 'what', 'time', 'ur', 'flight', 'tmr', 'what time', 'time is', 'is ur', 'ur flight', 'flight tmr'])
{'reverse': 11, 'is': 4, 'cheating': 0, 'that': 13, 'not': 9, 'mathematics': 8, 'reverse is': 12, 'is cheating': 5, 'cheating that': 1, 'that is': 14, 'is not': 6, 'not mathematics': 10, 'what': 20, 'time': 15, 'ur': 18, 'flight': 2, 'tmr': 17, 'what time': 21, 'time is': 16, 'is ur': 7, 'ur flight': 19, 'flight tmr': 3}
['Reverse is cheating. That is not mathematics.'
 'What time is ur flight tmr?']


In [31]:
X_vectors = vectorizer.transform(X[:10])
print(X_vectors.shape)
print(X_vectors)
print(X_vectors.toarray())

(10, 5)
  (0, 0)	1
  (0, 2)	1
  (0, 3)	1
  (1, 1)	1
  (1, 4)	1
[[1 0 1 1 0]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[1, 0, 2, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])